### ISSUE TITLE
Tranquil: Space for nav buttons are present even when nav buttons are disabled

### ISSUE THREAD

**Issue by ralsei** [monstrousdev/themes#11]
AFAIK, Linux builds of Discord don't have navigation buttons inbuilt due to the WM/DE handling that.
Not sure if this is detectable.
It leaves a pretty weird blank space.

![1578541952](https://user-images.githubusercontent.com/16062051/72036689-a3d7b880-3269-11ea-8c88-e8e82adb5d43.png)

**Comment by themonstrousdev** [comment]
I'll see how I can remedy that. Thanks for letting me know!

**Comment by themonstrousdev** [comment]
Should be fixed now
